/* Generated by scripts/gen-api-types.mjs — do not edit. */
export interface paths {
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect and recognise the foods in a photo */
        post: operations["scan_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search foods by name */
        get: operations["search_foods_v1_foods_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/barcode/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a packaged food */
        get: operations["barcode_v1_barcode__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meals in a date range */
        get: operations["list_meals_v1_meals_get"];
        put?: never;
        /** Log a meal */
        post: operations["create_meal_v1_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meal */
        get: operations["get_meal_v1_meals__meal_id__get"];
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_v1_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /** Edit a meal */
        patch: operations["update_meal_v1_meals__meal_id__patch"];
        trace?: never;
    };
    "/v1/summary/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Totals per day */
        get: operations["daily_summary_v1_summary_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pantry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your custom foods */
        get: operations["list_pantry_v1_pantry_get"];
        put?: never;
        /** Create Pantry Food */
        post: operations["create_pantry_food_v1_pantry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pantry/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Pantry Food */
        delete: operations["delete_pantry_food_v1_pantry__food_id__delete"];
        options?: never;
        head?: never;
        /** Update Pantry Food */
        patch: operations["update_pantry_food_v1_pantry__food_id__patch"];
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your goals and settings */
        get: operations["get_profile_v1_me_profile_get"];
        /** Put Profile */
        put: operations["put_profile_v1_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download all of your data as JSON */
        get: operations["export_data_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete your account */
        delete: operations["delete_account_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your conversation with the coach */
        get: operations["get_thread_v1_coach_thread_get"];
        put?: never;
        post?: never;
        /** Start over */
        delete: operations["clear_thread_v1_coach_thread_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message; the reply streams back as Server-Sent Events */
        post: operations["send_message_v1_coach_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/meal-insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A short tip about a logged meal */
        post: operations["meal_insight_v1_coach_meal_insight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body */
        Body: {
            /** Sex */
            sex?: ("female" | "male") | null;
            /** Birthyear */
            birthYear?: number | null;
            /** Heightcm */
            heightCm?: number | null;
            /** Weightkg */
            weightKg?: number | null;
            /** Activity */
            activity?: ("sedentary" | "light" | "moderate" | "active" | "very_active") | null;
        };
        /** Body_scan_v1_scan_post */
        Body_scan_v1_scan_post: {
            /**
             * Image
             * @description JPEG, PNG, WebP or HEIC
             */
            image: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "model";
            /** Text */
            text: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** CoachMessageIn */
        CoachMessageIn: {
            /** Message */
            message: string;
        };
        /** CoachThread */
        CoachThread: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** DailySummary */
        DailySummary: {
            /** Days */
            days: components["schemas"]["DaySummary"][];
        };
        /** DaySummary */
        DaySummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            totals: components["schemas"]["Macros"];
            /** Meals */
            meals: number;
        };
        /** FoodHit */
        FoodHit: {
            /**
             * Source
             * @enum {string}
             */
            source: "food101" | "pantry" | "calorieninjas";
            /**
             * Id
             * @description Pantry food id when source is `pantry`
             */
            id?: string | null;
            /**
             * Name
             * @description Stable key, e.g. a Food-101 class name
             */
            name: string;
            /** Display */
            display: string;
            /** Group */
            group?: string | null;
            per100g: components["schemas"]["Macros"];
            /** Servingg */
            servingG: number;
            /** Servinglabel */
            servingLabel?: string | null;
        };
        /** FoodSearchResponse */
        FoodSearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["FoodHit"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Models */
            models: boolean;
            /** Coach */
            coach: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * Macros
         * @description Energy and macronutrients for some amount of food.
         */
        Macros: {
            /** Kcal */
            kcal: number;
            /** Proteing */
            proteinG: number;
            /** Fatg */
            fatG: number;
            /** Carbsg */
            carbsG: number;
        };
        /** Meal */
        Meal: {
            /** Id */
            id: string;
            /**
             * Localdate
             * Format: date
             */
            localDate: string;
            /**
             * Mealtype
             * @enum {string}
             */
            mealType: "breakfast" | "lunch" | "dinner" | "snack";
            /**
             * Eatenat
             * Format: date-time
             */
            eatenAt: string;
            /**
             * Source
             * @enum {string}
             */
            source: "scan" | "barcode" | "pantry" | "search" | "manual";
            /** Items */
            items: components["schemas"]["MealItem"][];
            totals: components["schemas"]["Macros"];
            /** Photopath */
            photoPath?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** MealIn */
        MealIn: {
            /**
             * Localdate
             * Format: date
             * @description Calendar day in the user's timezone
             */
            localDate: string;
            /**
             * Mealtype
             * @enum {string}
             */
            mealType: "breakfast" | "lunch" | "dinner" | "snack";
            /** Eatenat */
            eatenAt?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "scan" | "barcode" | "pantry" | "search" | "manual";
            /** Items */
            items: components["schemas"]["MealItemIn"][];
            /** Photopath */
            photoPath?: string | null;
            /** Note */
            note?: string | null;
        };
        /** MealInsight */
        MealInsight: {
            /** Headline */
            headline: string;
            /** Tip */
            tip: string;
            /** Nextmealsuggestion */
            nextMealSuggestion: string;
        };
        /** MealInsightIn */
        MealInsightIn: {
            /** Mealid */
            mealId: string;
        };
        /** MealItem */
        MealItem: {
            /** Name */
            name: string;
            /** Display */
            display: string;
            /** Group */
            group?: string | null;
            /**
             * Label
             * @description Food-101 class if known
             */
            label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Grams */
            grams: number;
            /** Estimatedgrams */
            estimatedGrams?: number | null;
            per100g: components["schemas"]["Macros"];
            box?: components["schemas"]["NormBox"] | null;
            nutrition: components["schemas"]["Macros"];
        };
        /** MealItemIn */
        MealItemIn: {
            /** Name */
            name: string;
            /** Display */
            display: string;
            /** Group */
            group?: string | null;
            /**
             * Label
             * @description Food-101 class if known
             */
            label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Grams */
            grams: number;
            /** Estimatedgrams */
            estimatedGrams?: number | null;
            per100g: components["schemas"]["Macros"];
            box?: components["schemas"]["NormBox"] | null;
        };
        /** MealList */
        MealList: {
            /** Meals */
            meals: components["schemas"]["Meal"][];
        };
        /** MealPatch */
        MealPatch: {
            /** Localdate */
            localDate?: string | null;
            /** Mealtype */
            mealType?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Items */
            items?: components["schemas"]["MealItemIn"][] | null;
            /** Photopath */
            photoPath?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Detector */
            detector: string;
            /** Classifier */
            classifier: string;
        };
        /**
         * NormBox
         * @description Box as fractions of the image: top-left (x, y), width w, height h — all 0..1.
         */
        NormBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** PantryFood */
        PantryFood: {
            /** Name */
            name: string;
            /**
             * Servingg
             * @default 100
             */
            servingG: number;
            /** Servinglabel */
            servingLabel?: string | null;
            perServing: components["schemas"]["Macros"];
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Id */
            id: string;
            per100g: components["schemas"]["Macros"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Lastusedat */
            lastUsedAt?: string | null;
        };
        /** PantryIn */
        PantryIn: {
            /** Name */
            name: string;
            /**
             * Servingg
             * @default 100
             */
            servingG: number;
            /** Servinglabel */
            servingLabel?: string | null;
            perServing: components["schemas"]["Macros"];
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
        };
        /** PantryList */
        PantryList: {
            /** Foods */
            foods: components["schemas"]["PantryFood"][];
        };
        /** PantryPatch */
        PantryPatch: {
            /** Name */
            name?: string | null;
            /** Servingg */
            servingG?: number | null;
            /** Servinglabel */
            servingLabel?: string | null;
            perServing?: components["schemas"]["Macros"] | null;
            /** Favorite */
            favorite?: boolean | null;
        };
        /** Prediction */
        Prediction: {
            /**
             * Label
             * @description Food-101 class name, e.g. `caesar_salad`
             */
            label: string;
            /** Display */
            display: string;
            /** Group */
            group: string;
            /** Confidence */
            confidence: number;
            per100g: components["schemas"]["Macros"];
            /**
             * Suggestedgrams
             * @description Estimated portion if this guess is right
             */
            suggestedGrams: number;
            /**
             * Portionmethod
             * @enum {string}
             */
            portionMethod: "box_area" | "typical_serving";
        };
        /** Product */
        Product: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Group */
            group: string;
            /** Servingg */
            servingG?: number | null;
            /** Servinglabel */
            servingLabel?: string | null;
            per100g: components["schemas"]["Macros"];
            perServing?: components["schemas"]["Macros"] | null;
            /** Nutriscore */
            nutriScore?: ("a" | "b" | "c" | "d" | "e") | null;
            /** Novagroup */
            novaGroup?: number | null;
        };
        /** Profile */
        Profile: {
            /** Displayname */
            displayName?: string | null;
            /**
             * Goal
             * @default health
             * @enum {string}
             */
            goal: "lose" | "maintain" | "gain" | "health";
            targets: components["schemas"]["Targets"];
            body?: components["schemas"]["Body"] | null;
            /**
             * Units
             * @default metric
             * @enum {string}
             */
            units: "metric" | "imperial";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
            /** Createdat */
            createdAt?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
        };
        /** ProfileIn */
        ProfileIn: {
            /** Displayname */
            displayName?: string | null;
            /**
             * Goal
             * @default health
             * @enum {string}
             */
            goal: "lose" | "maintain" | "gain" | "health";
            targets: components["schemas"]["Targets"];
            body?: components["schemas"]["Body"] | null;
            /**
             * Units
             * @default metric
             * @enum {string}
             */
            units: "metric" | "imperial";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
        };
        /** ScanItem */
        ScanItem: {
            /** Id */
            id: string;
            /** @description Null when the whole photo was classified */
            box: components["schemas"]["NormBox"] | null;
            /** Detectorscore */
            detectorScore: number | null;
            /**
             * Needsconfirmation
             * @description True when the top guess is not confident
             */
            needsConfirmation: boolean;
            /**
             * Predictions
             * @description Best guess first
             */
            predictions: components["schemas"]["Prediction"][];
        };
        /** ScanResponse */
        ScanResponse: {
            /** Scanid */
            scanId: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Source
             * @enum {string}
             */
            source: "detector" | "full_image";
            /** Items */
            items: components["schemas"]["ScanItem"][];
            timings: components["schemas"]["ScanTimings"];
            models: components["schemas"]["ModelInfo"];
        };
        /** ScanTimings */
        ScanTimings: {
            /** Decodems */
            decodeMs: number;
            /** Detectms */
            detectMs: number;
            /** Classifyms */
            classifyMs: number;
            /** Totalms */
            totalMs: number;
        };
        /** Targets */
        Targets: {
            /** Kcal */
            kcal: number;
            /** Proteing */
            proteinG: number;
            /** Fatg */
            fatG: number;
            /** Carbsg */
            carbsG: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    scan_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_v1_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_v1_foods_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    barcode_v1_barcode__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_v1_meals_get: {
        parameters: {
            query: {
                /** @description First day (inclusive), YYYY-MM-DD */
                from: string;
                /** @description Last day (inclusive), YYYY-MM-DD */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_v1_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meal_v1_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_v1_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_v1_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_summary_v1_summary_daily_get: {
        parameters: {
            query: {
                /** @description First day (inclusive), YYYY-MM-DD */
                from: string;
                /** @description Last day (inclusive), YYYY-MM-DD */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pantry_v1_pantry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryList"];
                };
            };
        };
    };
    create_pantry_food_v1_pantry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryFood"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pantry_food_v1_pantry__food_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pantry_food_v1_pantry__food_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryFood"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    put_profile_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_data_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_account_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_thread_v1_coach_thread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachThread"];
                };
            };
        };
    };
    clear_thread_v1_coach_thread_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_message_v1_coach_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachMessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meal_insight_v1_coach_meal_insight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealInsightIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealInsight"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
