"""Storage interfaces, implemented by Firestore (production) and in-memory (tests, demos)."""

from __future__ import annotations

import datetime as dt
from typing import Any, Protocol

from app.schemas.coach import ChatMessage
from app.schemas.meals import Meal
from app.schemas.pantry import PantryFood
from app.schemas.profile import Profile


class ProfileRepo(Protocol):
    async def get(self, uid: str) -> Profile | None: ...
    async def put(self, uid: str, profile: Profile) -> Profile: ...


class MealRepo(Protocol):
    async def list_range(self, uid: str, start: dt.date, end: dt.date) -> list[Meal]: ...
    async def get(self, uid: str, meal_id: str) -> Meal | None: ...
    async def put(self, uid: str, meal: Meal) -> Meal: ...
    async def delete(self, uid: str, meal_id: str) -> bool: ...


class PantryRepo(Protocol):
    async def list(self, uid: str) -> list[PantryFood]: ...
    async def get(self, uid: str, food_id: str) -> PantryFood | None: ...
    async def put(self, uid: str, food: PantryFood) -> PantryFood: ...
    async def delete(self, uid: str, food_id: str) -> bool: ...


class CoachRepo(Protocol):
    async def recent(self, uid: str, limit: int) -> list[ChatMessage]: ...
    async def append(self, uid: str, message: ChatMessage) -> None: ...
    async def clear(self, uid: str) -> None: ...


class AccountRepo(Protocol):
    async def export(self, uid: str) -> dict[str, Any]: ...
    async def delete_all(self, uid: str) -> None: ...


class Repositories(Protocol):
    @property
    def profiles(self) -> ProfileRepo: ...
    @property
    def meals(self) -> MealRepo: ...
    @property
    def pantry(self) -> PantryRepo: ...
    @property
    def coach(self) -> CoachRepo: ...
    @property
    def account(self) -> AccountRepo: ...
